# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6b6a1d8db53690942cb4350de72ccfb48f20e8eeb78df43f682a4d493eb79d9e06ef5a6c9fea8a982b6fe92f0ab975df9054304ce389265054b19d7002cdeb0

test:
  secret_key_base: a7419e03c33c896b6a906d54510332ac0054c9fa87befd7b4937ea63fde7f71f7fbafb056f79499cd6e27b17891db0b77d16f487ef1691ce61252abe4177d984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
